training_texts = [
    "The quick brown fox jumps over the lazy dog.",
    "The dog barks at the fox.",
    "A swift breeze flows over the quiet lake.",
    "Bright stars twinkled in the night sky.",
    "The sun sets behind the distant mountains.",
    "Rain pattered against the window panes.",
    "Leaves rustled as the wind passed through the trees.",
    "Waves crashed against the shore in a rhythmic pattern.",
    "The moon cast a silvery glow over the tranquil garden.",
    "A chorus of frogs sang in the wetlands.",
    "Fireflies danced in the warm summer night.",
    "The cat curled up in the sunbeam, purring contently.",
    "A gentle snowfall blanketed the town in white.",
    "The train whistled as it chugged along the tracks.",
    "Clouds meandered across the serene blue sky.",
    "The clock ticked away, marking the passage of time.",
    "An owl hooted in the forest, a sound that echoed in the silence.",
    "The river wound its way through the valley, a ribbon of blue.",
    "The garden was a riot of color, with flowers blooming in every hue.",
    "The old bookshop smelled of musty pages and stories long forgotten."
]

sci_fi_texts = [
    "The spaceship landed on the alien planet.",
    "Advanced technology allowed for interstellar travel.",
    "Robotic sentinels patrolled the desolate wasteland.",
    "The time portal flickered, hinting at alternate realities.",
    "Cybernetic implants enhanced human capabilities beyond natural limits.",
    "The hologram projected a 3D map of the galaxy.",
    "Artificial intelligence governed the utopian society.",
    "Quantum computers solved complex equations in nanoseconds.",
    "The terraforming process created a breathable atmosphere on Mars.",
    "Space elevators transported materials between Earth and the orbital station.",
    "Alien languages were deciphered using advanced cryptography.",
    "Nanobots repaired damaged tissue, revolutionizing medicine."
]

fantasy_texts = [
    "The wizard cast a powerful spell on the dragon.",
    "Elves and dwarves joined forces to defeat the dark lord.",
    "A lone knight embarked on a quest to retrieve the enchanted chalice.",
    "The ancient prophecy foretold the rise of a hero from humble beginnings.",
    "Mystical runes glowed on the ancient artifact, sealing away its magic.",
    "The sorceress summoned a phoenix from the ashes to aid in battle.",
    "In the enchanted forest, trees whispered secrets of the old magic.",
    "A band of adventurers uncovered a hidden realm through a magical portal.",
    "The kingdom's fate hung in the balance, protected by the guardian dragons.",
    "A cloak of invisibility was the thief's key to the treasure vault.",
    "The prince was cursed to slumber until awakened by true love's kiss.",
    "Goblins and trolls clashed in the depths of the shadowy caverns.",
    "The fairy queen held court in the heart of the shimmering glade."
]

romance_texts = [
    "Her heart fluttered as their eyes met across the crowded room.",
    "Under the soft glow of the moonlight, they shared a tender kiss.",
    "He held her hand gently, their fingers entwined as they walked along the beach.",
    "A bouquet of red roses lay on her doorstep, a secret admirer's confession.",
    "They danced through the night, lost in the rhythm and each other's embrace.",
    "Love letters exchanged over years, a testament to their undying affection.",
    "The proposal was a surprise, a moment of pure romance under the starlit sky.",
    "A chance encounter turned into a whirlwind romance that defied all odds.",
    "In the quiet of the library, their love story began with a shared glance.",
    "The locket held an old photograph, a precious memory of their timeless love."
]

ngram_training_texts = [
    "The sun set behind the mountains, painting the sky in hues of orange and pink.",
    "Children played in the park, their laughter echoing through the air.",
    "A gentle breeze rustled the leaves, creating a soothing melody.",
    "The city streets were bustling with activity, cars honking and people chatting.",
    "In the quiet of the night, the stars twinkled like diamonds in the sky.",
    "The aroma of freshly baked bread filled the kitchen, making everyone's mouth water.",
    "Birds chirped merrily in the morning, welcoming the new day.",
    "The old man sat on the bench, feeding the pigeons with a smile on his face.",
    "Raindrops tapped against the window, a rhythmic lullaby for those inside.",
    "The library was a haven of peace, with rows upon rows of books waiting to be explored.",
    "A cat curled up by the fireplace, purring contentedly as it drifted off to sleep.",
    "The market was alive with colors and sounds, vendors calling out their wares.",
    "A train whistled in the distance, signaling its arrival at the station.",
    "The beach was a paradise, with golden sands and crystal-clear waters.",
    "A musician played a soulful tune on the street corner, captivating passersby.",
    "The garden was a riot of color, with flowers blooming in every hue.",
    "A couple strolled hand in hand, lost in their own world.",
    "The forest was a symphony of sounds, with birds singing and leaves rustling.",
    "A painter captured the beauty of the landscape on his canvas.",
    "The bakery was a treasure trove of delights, with cakes and pastries of all kinds.",
    "A dog barked happily as it chased a ball across the yard.",
    "The river wound its way through the valley, a ribbon of blue.",
    "A writer sat at her desk, lost in the world of her imagination.",
    "The mountains stood tall and majestic, a testament to nature's grandeur.",
    "A child built a sandcastle on the beach, complete with towers and a moat.",
    "The café was a cozy retreat, with the aroma of coffee and the hum of conversation.",
    "A butterfly flitted from flower to flower, a delicate dance in the garden.",
    "The clock tower chimed the hour, its sound echoing through the town.",
    "A fisherman cast his line into the lake, hoping for a good catch.",
    "The meadow was a sea of green, dotted with wildflowers swaying in the breeze.",
    "A seamstress worked diligently, her needle and thread creating beautiful patterns.",
    "The bookstore was a labyrinth of shelves, each one filled with stories waiting to be discovered.",
    "A horse galloped across the field, its mane flowing in the wind.",
    "The sunset painted the sky in a breathtaking array of colors.",
    "A chef prepared a gourmet meal, his hands moving with practiced skill.",
    "The playground was filled with the joyful sounds of children at play.",
    "A gardener tended to her plants, nurturing them with care and love.",
    "The ocean waves crashed against the shore, a powerful and mesmerizing sight.",
    "A photographer captured the perfect moment, freezing it in time.",
    "The village was a picture of tranquility, with quaint houses and cobblestone streets.",
    "A dancer moved gracefully across the stage, her movements telling a story.",
    "The campfire crackled and popped, its warmth a comfort on a chilly night.",
    "A poet found inspiration in the beauty of nature, crafting verses that spoke to the soul.",
    "The city skyline was a dazzling display of lights, a testament to human ingenuity.",
    "A traveler explored new lands, eager to discover the wonders of the world.",
    "The orchestra played a symphony, the music filling the concert hall with emotion.",
    "A baker kneaded dough, preparing it for the oven.",
    "The rain washed away the dust, leaving the world fresh and clean.",
    "A teacher guided her students, imparting knowledge and wisdom.",
    "The festival was a celebration of culture, with music, dance, and food from around the world."
]

